### ISSUE TITLE
Wrong architecture for ARM docker image

### ISSUE THREAD

**Issue by N0ciple** [1activegeek/docker-airconnect#15]
Hello,

After the last update (the one published a few hours ago) the ARM version is no longer working. A `docker logs airconnect` yields the following message  : 
```
[...]
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
[...]
```

This is typically the error message that we got when the architecture of the docker image is not the same as the host system.

I run the docker image on a Raspberry Pi 4 running raspbian 10.
Lest me know if you want more info/test from my side!

**Comment by 1activegeek** [comment]
Thanks for reporting this. I just went back to address this since someone pointed out the other arch formats were not being updated. I stupidly did this backward and set Docker Hub to pull the dockerfile and build, rather than use the GitHub multi-arch. Can you try pulling a fresh copy now and let me know if that works? I just ran a build on GH and it has pushed up to DockerHub. I'm making an adjustment to the GitHub Actions file so that it will schedule the update on a weekly basis to ensure at most the code is no more than 1 week old from the mainline code from the originating project.

**Comment by 1activegeek** [comment]
Just finished checking after updating the GH Action with the cron schedule. Looks like all builds are passing and pushing to DH. Please reply here and let me know what happens, but for now I'll mark this closed as I anticipate it should be all cleared up now. If anyone else comes upon this and can validate, please feel free to respond as well.

**Comment by N0ciple** [comment]
I just pulled the new image (latest-arm) and made I quick test. I can confirm it is now working correctly for ARM (tested on Raspberry PI 4, Raspian 10).
Thanks a lot 😉 !

**Comment by 1activegeek** [comment]
Perfect! Thanks for checking back in. Sorry for the disruption from my lack of focus. 😄
