### ISSUE TITLE
Is there a way to get docker-airconnect to map to specific ports (firewall)

### ISSUE THREAD

**Issue by MrSimmo** [1activegeek/docker-airconnect#23]
I'm running docker-airconnect behind a firewall (UFW); is there a way to specify or limit the ports it listens on so I can allow these through the firewall?

**Comment by 1activegeek** [comment]
I do not believe there is a way to specify or limit the ports. By the very nature of the app, it is using mDNS and is meant to be a bit of a plug n play type of auto configuration for the devices. This means ports will easily change and shift. The original app documentation illustrates not to use firewall between devices and the app. Many however have done it I believe, and will require digging into the ports used so that it can communicate properly. I'd suggest maybe searching through the original app issues list for others who've hit similar issues.

**Comment by MrSimmo** [comment]
Ok np 👍
