### ISSUE TITLE
How can I hide devices from list?

### ISSUE THREAD

**Issue by TrueCitrus** [1activegeek/docker-airconnect#4]
How can I hide devices from showing up on the  list of Airplay targets?
My TV and other devices are incorrectly showing up as Airplay targets and I'd like to clean up the list. Thanks

**Comment by 1activegeek** [comment]
You can refer to the software creators information on this: https://github.com/philippe44/AirConnect#config-file-parameters. Unfortunately I've just packaged up the code into a docker container.

As for devices you indicate are "incorrectly" showing up, I'd suggest they are actually correct. The software is very simple in what it does - create airplay targets for upnp/dlna media players it finds on your network. The devices discovered are likely just that, media playback capable. Most TV's these days include this type of functionality for example OOTB. So while you may not want them to appear, they're appearing due to auto-discovery of such services.
