### ISSUE TITLE
AIRUPNP_VAR=kill on UnRaid Docker

### ISSUE THREAD

**Issue by jompjomp** [1activegeek/docker-airconnect#40]
I’ve tried multiple ways, but I just can’t figure out how to stop the UPNP part from running on UnRaid. I’m sure it’s something simple, but how do I pass the “ AIRUPNP_VAR=kill” command to airconnect?

Any help is very much appreciated!

**Comment by 1activegeek** [comment]
Unfortunately I don't have an unRAID host anymore, so I can't comment on the specifics of how you would add an environment variable to a container. I'd try and look for help specifically on the unRAID forums on how to insert Environment Variables for a container. AFAIK the feature is working and working as expected as I utilize this exact function to disable AIRUPNP in my own running version of this container currently - however that is using straight docker compose on the command line, not an unRAID GUI.

If you can get the variable inserted, and it's still not working - feel free to re-open the issue here and I can try to assist.
