### ISSUE TITLE
Can't run latest version

### ISSUE THREAD

**Issue by Camotoy** [1activegeek/docker-airconnect#62]
Hello!

Docker logs when running from the latest tag appear as such:

```
[migrations] started
[migrations] no migrations found
/package/admin/s6-overlay-3.1.6.2/etc/s6-rc/scripts/cont-init: 20: /etc/cont-init.d/30-install: Permission denied
usermod: no changes
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____
      | __  |  |  | |  |  |    \
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/

  Based on images from linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

[custom-init] No custom files found, skipping...
s6-supervise airconnect: warning: unable to spawn ./run (waiting 60 seconds): Permission denied
[ls.io-init] done.[migrations] started
[migrations] no migrations found
/package/admin/s6-overlay-3.1.6.2/etc/s6-rc/scripts/cont-init: 20: /etc/cont-init.d/30-install: Permission denied
usermod: no changes
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____
      | __  |  |  | |  |  |    \
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/

  Based on images from linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

[custom-init] No custom files found, skipping...
s6-supervise airconnect: warning: unable to spawn ./run (waiting 60 seconds): Permission denied
[ls.io-init] done.
```

Run command: `docker run --name "airconnect" -d --net=host --restart unless-stopped 1activegeek/airconnect`

1.7.0 works fine.

I'm no Docker expert so I apologize if I did something wrong! I did note the image on Dockerhub was recently updated.

**Comment by Flyinace2000** [comment]
Same error here
"s6-supervise airconnect: warning: unable to spawn"

Running via UnRaid on intel hardware.

**Comment by 1activegeek** [comment]
Thank you for reporting. Looks like I'm seeing too. I'll have to dig into this. Odd that it's a permissions based issue it seems. Probably something changed in the base image. I'll have to do some research. For the moment I'll have to see if I can revert my latest back and hold the automated build until I can fix this manually. Short term, as noted - please use the previous version tag.

**Comment by 1activegeek** [comment]
@Flyinace2000 @Camotoy I've had to restructure a bit so there is possibility for a lot of unknown scenarios I'd already accounted for in my previous version since this is a totally different S6 setup. Can you please take a stab at testing out the `dev` branch of the container on Docker hub? Try with different devices, modifications, etc if you can just to help me validate it's working properly now. My first initial test seemed to run properly - but I don't pass any arguments, modify, etc.

**Comment by jacoknapp** [comment]
as far as i can tell the dev branch is working. There is a bug in ios 18 that has issues with airplay 1. that will hopefully get fixed in the next beta, so i can't test end to end. I can see the mdns broadcast be sent out, and everything binds correctly, plus the binary for aircast is running correctly.  Proxmox, lxc container, running ubuntu 22.04.4, using a docker deployment

**Comment by 1activegeek** [comment]
@jacoknapp thanks for the report. Ya I have the same issue running iOS 18 beta. Had to use my MacBook not running beta to validate. 😄

**Comment by jacoknapp** [comment]
I did notice higher CPU usage in the dev version, like it's not taking a full core in the lxc container I have dedicated for this. ![image](https://github.com/user-attachments/assets/a83aa37b-01a2-4b20-b600-32286257c67c)![image](https://github.com/user-attachments/assets/b9cbfb47-d052-4062-8d9d-73ea7e953f6b)

**Comment by 1activegeek** [comment]
Interesting - I might have to create another branch to test that pulls an older version of the airconnect app, but uses the new run format. I can't imagine adjusting my s6 usage should be causing that large of a difference - but I think comparing with an older version of the airconnect app is only true way to see if its the container or the app. i'll get back to this, but might take a week or so to jump back into.

**Comment by jacoknapp** [comment]
Just picking this back up, now that the beta is fixed. It does appear to be use 1 core while just idle. Which is weird, but running this for a while and haven't seen this before.

**Comment by 1activegeek** [comment]
Thanks for checking back in. Good news, the `latest` tag should put you back into the current working version. I've gotta get some time to run a test pushing the old airconnect version into the new container format I'm using. Find out if it's airconnect or its my container. Will update here once I get it checked out.

**Comment by 1activegeek** [comment]
@jacoknapp believe I've found the culprit and fixed it. Please take a stab at pulling the dev image again.

I also made a change to how I was naming the binary - hoping I didn't break this for non-x86 users 😬

@Camotoy @Flyinace2000 if you don't mind also testing out the dev branch to see how it performs. AFAIK this looks to be working solid with my setup (customer aircast var, and killing airupnp). Tried a few other permutations and by all accounts it looked fine. 

Going to give this a few weeks in hopes folks get a chance to further test the dev branch.

**Comment by jacoknapp** [comment]
Unfortunately, I’m still seeing it 100% a single core :-/On Aug 22, 2024, at 7:07 PM, Shawn Mix ***@***.***> wrote:﻿
@jacoknapp believe I've found the culprit and fixed it. Please take a stab at pulling the dev image again.
I also made a change to how I was naming the binary - hoping I didn't break this for non-x86 users 😬
@Camotoy @Flyinace2000 if you don't mind also testing out the dev branch to see how it performs. AFAIK this looks to be working solid with my setup (customer aircast var, and killing airupnp). Tried a few other permutations and by all accounts it looked fine.
Going to give this a few weeks in hopes folks get a chance to further test the dev branch.

**Comment by 1activegeek** [comment]
@jacoknapp can you confirm:
- You pulled the latest dev tag from Docker Hub (not locally built from GH repo?)
- Confirm the ImageID or digest on the image
- Share your architecture (arm vs x86)
- Are you using any AIR(CAST/UPNP)_VAR variables? 
- Can you share the startup logs from a `docker logs airconnect` command

**Comment by jacoknapp** [comment]
Ahhh yeah, that's on me. I didn't have a docker-compose pull before my docker-compose up in my deployment pipeline. Don't deploy this one frequently and must have missed it! It's using the correct amount of cpu now. Out of curiosity what was the issue?

**Comment by 1activegeek** [comment]
😅 Phew ... 
Sadly I'm puzzled - the actual binary has a `non-interactive` mode flag. I did NOT have this flag in my older version that is working, but it wasn't consuming the CPU like crazy. This new version though, I had to add this in so it wouldn't stay in running state consuming max cpu. 
Funny enough, he calls it out right in his readme too:
```
Use of -z disables interactive mode (no TTY) and self-daemonizes (use -p <file> to get the PID). Use of -Z only disables interactive mode
Do not daemonize (using & or any other method) the executable w/o disabling interactive mode (-Z), otherwise it will consume all CPU. On Linux, FreeBSD and Solaris, best is to use -z. Note that -z option is not available on MacOS or Windows
```
🤷🏻‍♂️  After spending way too much time scratching my brain ... I'll take the win and not worry about how it magically worked before 😆

**Comment by jacoknapp** [comment]
Oh! Honestly I am surprised that ever worked too! I ran this before I switched over to docker for everything and it was a hard requirement. But it’s fixed now, so we should be good! Cheers and thanks for spending the time bug fixing this! On Aug 22, 2024, at 9:12 PM, Shawn Mix ***@***.***> wrote:﻿
😅 Phew ...
Sadly I'm puzzled - the actual binary has a non-interactive mode flag. I did NOT have this flag in my older version that is working, but it wasn't consuming the CPU like crazy. This new version though, I had to add this in so it wouldn't stay in running state consuming max cpu.
Funny enough, he calls it out right in his readme too:
Use of -z disables interactive mode (no TTY) and self-daemonizes (use -p <file> to get the PID). Use of -Z only disables interactive mode
Do not daemonize (using & or any other method) the executable w/o disabling interactive mode (-Z), otherwise it will consume all CPU. On Linux, FreeBSD and Solaris, best is to use -z. Note that -z option is not available on MacOS or Windows

🤷🏻‍♂️  After spending way too much time scratching my brain ... I'll take the win and not worry about how it magically worked before 😆

**Comment by Camotoy** [comment]
The latest tag is working correctly for me, and I'm not seeing any intensive CPU usage.

**Comment by 1activegeek** [comment]
> The latest tag is working correctly for me, and I'm not seeing any intensive CPU usage.

@Camotoy were you able to test out the `dev` tag - the `latest` tag should be working because I made a temporary fix to avoid mainstream issues while I worked on a true resolution. The `dev` tag is the new release which will become `latest` once I push the change. Just trying to get a few other eyes on things to validate/confirm the fix is working in different setups. If you can take a moment and test it out for me. Would be greatly appreciated.

**Comment by 1activegeek** [comment]
Closing as the fix has now been deployed into master branch. Please let me know of any issues if anyone hits any snags on the master branch now.
